package wookie

import (
	"fmt"
	"strings"
	"testing"

	. "github.com/smartystreets/goconvey/convey"
)

var wookieData = strings.Split(`AAAAACAAAAGAAAATAAAC
AAGCAAAGGAAAGTAAA
AAGTGAAGTTAATACAATAGAAT
ACACGACACTACAGCACAGGACAGTACAT
ACCTGACCTTACGAGACGATACGCCACGCG
ACGCGACGCTACGGCACGGGACGGTAC
AGACTATACTCCACTCGACTCT
AGGCTAGGGCAGGGGAGGGTAGGTCAGGT
AGTAGATCAGATGAGATTAGCATAGCCC
ATTAGCATAGCCCAGCCGAGCCTAGCG
ATTCAATTGAATTTACACCACACG
CAACAGAACATAACCCAACCGA
CAGTCGAGTCTAGTGCAGTGGAGTGTAGTTCAG
CCATACCCCACCCGACCCTACC
CCATGCGATGCTATGGCATGGGATGGTATGT
CCTACCGCACCGGACCGTACCTCACCT
CCTAGCGCAGCGGAGCGTAGCTCAGCTGAGCTTA
CCTCCCGGCCCGTCCCTGCCCTTCCGCGCCGCTCC
CGAACCTAACGCAACGGAAC
CTTAAGACAAGAGAAGATAAGCC
CTTTGCTTTTGGGGGTGGGTTGGTGTGGT
GAACGTAACTCAACTGAACTTA
GATATTATCCCATCCGATCCTATCGCATCGGAT
GCTCCGGGCCGGTCCGTGCCGTTCCTCGCCT
GCTGAGCTTAGGATAGGCCAGGCGAGGCT
GGTACGTCACGTGACGTTACTAGACT
GTAAATCAAATGAAATTAACACAACAG
GTACATCACATGACATTACCAGACCATACC
GTATGTCATGTGATGTTATTCCATT
GTGTGGTTTGTGTTGTTTT
TAAACCAAACGAAACTAAAGCA
TAAGCCAAGCGAAGCTAAGG
TAAGGCAAGGGAAGGTAAGTCAAGTGA
TAGAATATAATCCAATCGAATCTAATGC
TAGTTCAGTTGAGTTTATATCATATGATATTA
TCAGGTGAGGTTAGTATAGTCCAG
TCGCCTCTCCTGGCCTGTCCTTGCCTTTCGCG
TCGGATCGTATCTCATCTGATCTTATGCCAT
TCGTCTCGTGGCGTGTCGTTGCG
TCTAATGCAATGGAATGTAATTCAA
TCTACTGCACTGGACTGTACTTCACTTG
TCTGGGCTGGTCTGTGCTGTTCTTGGCTTGTCTTTGCT
TGTCGTTGCGTTTCTCTGCTCTTCTGGGC
TTCCATTCGATTCTATTGCATTGGATTGTAT
TTCGCGGCGCGTCGCTGCGCTTCGG
TTCGGCTCGGGGCGGGTCGGTGCGGTTCGTCTCG
TTGACTTTAGAGCAGAGGAGAGTAG
TTGTATTTCATTTGATTTTCCCCCGCCCCTCCC`, "\n")

func Test(t *testing.T) {
	Convey("Testing Wookie", t, func() {
		wookie := NewWookie(wookieData)
		wookie.Compute()
		//fmt.Println(wookie)
		genomes := wookie.GetGenomes()
		So(len(genomes), ShouldNotEqual, 0)
		for _, genome := range genomes {
			fmt.Println(genome.String())
		}
	})
}
